config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'about' => "pages#about"
  get 'contact' => "pages#contact"
  
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		  has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg"
		else
  has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
  					:storage => :dropbox,
  					:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  					:path => ":style/:id_:filename"
  	
  end
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
#  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :image, :content_type => /\Aimage\/.*\Z/  

  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :name, presence: true

    has_many :listings, dependent: :destroy
    has_many :sales, class_name: "Order", foreign_key: "seller_id"
    has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    if current_user.recipient.blank?
      Stripe.api_key = ENV["STRIPE_API_KEY"]
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => current_user.name,
        :type => "individual",
        :bank_account => token
        )
    end

    current_user.recipient = recipient.id
    current_user.save

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user.id != @listing.user_id
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else."
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales 
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:alert] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      :currency => "usd",
      :recipient => @seller.recipient
      )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

		html = <<-HTML
		<div data-alert class="alert-box alert">
			<a href="#" class="close">&times;</a>
			<h5>#{sentence}</h5>
			#{messages}
		</div>
		HTML
		
		html.html_safe
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="small-12 columns" role="contentinfo">
	<div class="row center">
		<p>&copy; Copyright 2014</p>
	</div><!-- .row -->
</footer><!-- .small-12 columns -->

app/views/layouts/_header.html.erb
<header class="contain-to-grid" role="banner">
	<div class="row">
		<nav class="top-bar" data-topbar role="navigation">
		  <ul class="title-area">
		    <li class="name">
		      <h1><a href="/">EtsyDemo</a></h1>
		    </li>
		    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
		  </ul>

		  <section class="top-bar-section">
		    <!-- Right Nav Section -->
		    <ul class="right">
		    	<% if user_signed_in? %>
			    	<li class="has-dropdown"><a href="#">Seller Account</a>
		    			<ul class="dropdown">
							<li><%= link_to "Manage Listings", seller_path %></li>
							<li><%= link_to "Sales History", sales_path %></li>
						</ul>
					</li>

					<li class="has-dropdown"><a href="#"><%= current_user.name %></a>
		    			<ul class="dropdown">
			    			<li><%= link_to "Purchase History", purchases_path %></li>
			    			<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
							<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
					      <% else %>
				    <li class="has-dropdown"><a href="#"><i class="fa fa-user"></i></a>
			    		<ul class="dropdown">
						    <li><%= link_to "Login", new_user_session_path %></li>
						    <li><%= link_to "Sign Up", new_user_registration_path %></li>
						</ul>
					</li>
				<% end %>
		    </ul><!-- .right section -->

		    <!-- Left Nav Section -->
		    <ul class="left">
		      <li><%= link_to "About", about_path %></li>
		      <li><%= link_to "Contact", contact_path %></li>
		    </ul>
		  </section><!-- .left section -->
		</nav><!-- .top-bar -->
	</div><!-- .row -->
</header><!-- .contain-to-grid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "EtsyDemo" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "https://js.stripe.com/v2" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  </head>

  <body>

	<%= render 'layouts/header' %>

	<div class="row">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div data-alert class="alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <a href="#" class="close">&times;</a>
        </div><!-- .alert-box -->
      <% end %>
    <% end %>
  </div><!-- .row -->

  <div class="row">
	    <%= yield %>
  </div><!-- .row -->

  <%= render 'layouts/footer'  %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div data-alert id="error_explanation" class="alert-box alert">
      <a href="#" class="close">&times;</a>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="stripe_error" class="alert-box alert" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
    </noscript>
  </div><!-- #stripe_error -->

  <div class="row no-padding">
    <div class="large-6 columns">
      <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "Enter your item's name here" %>
          </div>
      </div><!-- .columns -->

    <div class="large-2 columns">
      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price, placeholder: "100.00" %>
      </div>
    </div><!-- .columns -->

    <div class="large-4 columns">
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    </div><!-- .columns -->
  </div><!-- .row -->

  <div class="row no-padding">
    <div class="small-12 columns">
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, placeholder: "Enter your item's description here" %>
      </div>
    </div><!-- .columns -->
  </div><!-- .row -->

  <% if current_user.recipient.blank? %>
    <br>
    <h1>Back Account Information</h1>

    <div class="row no-padding">
      <div class="large-2 columns">
        <div class="field">
          <%= label_tag :country %>
          <%= text_field_tag :country, nil, {:name => nil, :'data-stripe' => "country", :placeholder => "US"} %>
        </div>
      </div><!-- .columns -->

      <div class="large-5 columns">
        <div class="field">
          <%= label_tag :routing_number %>
          <%= text_field_tag :routing_number, nil, {:name => nil, :'data-stripe' => "routingNumber", :placeholder => "9-digit Routing Number"} %>
        </div>
      </div><!-- .columns -->

      <div class="large-5 columns">
        <div class="field">
          <%= label_tag :account_number %>
          <%= text_field_tag :account_number, nil, {:name => nil, :'data-stripe' => "accountNumber", :placeholder => "Up to 17-digit Account Number"} %>
        </div>
      </div><!-- .columns -->
    </div><!-- .row -->
  <% end %>
  
  <div class="actions">
    <%= f.submit class: "button tiny" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="small-12 columns">
  <section id="homepage-hero" class="row">
      <h1>Handcrafted items from <br/> around the world.</h1>
      <h3>Discover one of a kind items</h3>
  </section>
</div><!-- .columns -->

<div class="small-12 columns">
  <div class="row center">
    <% @listings.each do |listing| %>
      <div class="item-listing medium-3 large-3 columns">
        <div class="panel" data-equalizer-watch>
          <%= link_to image_tag(listing.image.url), listing %>
            <div class="caption">
              <h3><%= listing.name %></h3>
              <p><%= number_to_currency(listing.price) %></p>
              <p><%= "Sold by #{listing.user.name}" %></p>
          </div><!-- .caption -->
        </div><!-- .panel -->
      </div><!-- .columns -->
    <% end %>
  </div><!-- .row -->
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, data: {no_turbolink: true} %>
<% end %>
</div><!-- .columns -->

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<div class="small-12 columns">
  <div class="row center">
    <table class="small-12 columns" role="grid">
      <tr>
        <th class="center">Image</th>
        <th class="center">Name</th>
        <th class="center">Description</th>
        <th class="center">Price</th>
        <th class="center">Action</th>
      </tr>

      <% @listings.each do |listing| %>
        <tr>
          <td><%= image_tag listing.image.url(:thumb) %></td>
          <td><%= listing.name %></td>
          <td><%= listing.description %></td>
          <td><%= number_to_currency(listing.price) %></td>
          <td>
            <button class="tiny button radius" data-dropdown="tinyDrop" aria-controls="tinyDrop" aria-expanded="false">Actions &raquo;</button>
              <ul id="tinyDrop" class="tiny f-dropdown" data-dropdown-content>
                  <li class="center"><%= link_to "View", listing %></li>
                  <li class="center"><%= link_to "Edit", edit_listing_path(listing) %></li>
                  <li class="center"><%= link_to "Destroy", listing, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul><!-- .tinyDrop -->
          </td>
        </tr>
      <% end %>
    </table>
  </div><!-- .row -->
</div><!-- .columns -->
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path , data: {no_turbolink: true}%>
<% end %>
</div><!-- .columns -->

app/views/listings/show.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= image_tag @listing.image.url %>
	</div><!-- .columns -->
	<div class="large-6 columns">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<div class="center">
			<br>
			<%= link_to "Buy It Now", new_listing_order_path(@listing), class: "button medium", data: {no_turbolink: true} %>
		</div><!-- .center -->
	</div><!-- .columns -->
</div><!-- .row -->

<% if current_user == @listing.user %>
	<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>	
<%= link_to 'Back', listings_path %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="large-4 columns">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div><!-- .thumbnail -->
    <h3><%= @listing.name %></h3>
    <h5><%= number_to_currency(@listing.price) %></h5>
  </div><!-- .columns -->

    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation"  class="alert-box alert">
          <a href="#" class="close">&times;</a>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div><!-- .alert-box -->
      <% end %>

      <div class="large-8 columns">

        <div id="stripe_error" class="alert-box alert" style="display:none">
          <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
          </noscript>
        </div><!-- #stripe_error -->

        <div class="field">
          <%= f.label :address %>
          <%= f.text_field :address, placeholder: "Enter your full street address here, include Apt/Suite" %>
        </div>

        <div class="row no-padding">
          <div class="large-6 columns">
            <div class="field">
              <%= f.label :city %>
              <%= f.text_field :city, placeholder: "Enter city here" %>
            </div>
          </div><!-- .columns -->

          <div class="large-6 columns">
            <div class="field">
              <%= f.label :state %>
              <%= f.text_field :state, placeholder: "2 letter state (ie: CA)" %>
            </div>
          </div><!-- .columns -->
        </div><!-- .row -->

        <div class="row no-padding">
          <div class="large-5 columns">
            <div class="field">
              <%= label_tag :card_number, "Credit Card Number" %>
              <%= text_field :card_number, nil, {:name => nil, :'data-stripe' => "number", :placeholder => "12-19 digit Card Number"} %>
            </div>
          </div><!-- .columns -->

          <div class="large-3 columns">
            <div class="field">
              <%= label_tag :card_code, "CVC" %>
              <%= text_field :card_code, nil, {:name => nil, :'data-stripe' => "cvc", :placeholder => "3-digit CVC"} %>
            </div>
          </div><!-- .columns -->

          <div class="large-2 columns"> 
            <div class="field">
              <%= label_tag nil, "Exp. Month" %>
              <%= select_month nil, {use_two_digit_numbers: true}, {:name => nil, :'data-stripe' => "exp-month"} %>
            </div>
          </div><!-- .columns -->

          <div class="large-2 columns">
            <div class="field">
              <%= label_tag nil, "Exp. Year" %>
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {:name => nil, :'data-stripe' => "exp-year"} %>
            </div>
          </div><!-- .columns -->
        </div><!-- .row -->

        <div class="actions">
          <%= f.submit "Complete Order", class: "button tiny success" %>
        </div>
      </div><!-- .columns -->
    <% end %>
</div><!-- .row -->

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listing_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="small-12 columns">
  <div class="row center">
    <h2>Your Purchase History</h2>
    <table class="small-12 columns" role="grid">
      <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Seller</th>
        <th class="center">Date Purchased</th>
      </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.seller.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>
  </div><!-- .row -->
</div><!-- .columns -->
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, data: {no_turbolink: true} %>
<% end %>
</div><!-- .columns -->

app/views/orders/sales.html.erb
<div class="small-12 columns">
  <div class="row center">
    <h2>Your Sales History</h2>
    <table class="small-12 columns" role="grid">
      <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Sold</th>
      </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.buyer.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>
  </div><!-- .row -->
</div><!-- .columns -->
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, data: {no_turbolink: true} %>
<% end %>
</div><!-- .columns -->

app/views/pages/about.html.erb
<h1>Welcome to EtsyDemo!</h1>
<h2>EtsyDemo is an online marketplace for buying and selling handmade goods.</h2>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Questions and concerns, email us at email@etsydemo.com</p>